Add helper class to limit messages in a channel
hwsuk/discord-bot pull request #14
Opened 2020-10-16 10:15 UTC by jzyrobert

2020-10-16 11:06 UTC, pessimist101 requested changes
The cog needs a setup function

2020-10-16 16:43 UTC, issy approved these changes

2020-10-16 16:44 UTC, jzyrobert commented
ship it

2020-10-17 09:50 UTC, issy commented
Needs testing

2020-10-17 13:55 UTC, merged