feat(embedremover): Remove embeds from all messages in a channel
hwsuk/discord-bot pull request #42
Opened 2021-01-25 20:07 UTC by jzyrobert

If the feedback is accepted

2021-01-26 16:03 UTC, jzyrobert commented
Can be done through discord perms

2021-01-29 12:47 UTC, jzyrobert commented
Apparently didnt work with perms

2021-02-05 22:08 UTC, bitshiftsdotio requested changes

2021-02-05 22:08 UTC, bitshiftsdotio commented on unity_cogs/embedremover.py
> +        print('Renderdistance meme cog online')
Make sure the log message is correct. Eventually I will break this out into a utility decorator which does this automatically, but for now please change it.

2021-02-05 22:10 UTC, bitshiftsdotio commented on unity_cogs/embedremover.py
> +        print('Renderdistance meme cog online')
Also, use `logging.info`

2021-02-05 22:17 UTC, bitshiftsdotio approved these changes

2021-02-05 22:17 UTC, merged