feat/react_report: Add message reporting by adding "⚠️" reaction
hwsuk/discord-bot pull request #45
Opened 2021-02-13 19:12 UTC by bitshiftsdotio

This PR enables users to report messages to moderators by adding a ⚠️ reaction to any message. It will save some information about the message to MongoDB, and create an embed in a moderator-only channel. If the message is removed or all ⚠️ reactions are removed, the information in the database is removed too.

<img width="341" alt="Screenshot 2021-02-13 at 19 12 36" src="https://user-images.githubusercontent.com/25872549/107859154-74618b00-6e2f-11eb-8344-10a5ca104ef3.png">

2021-02-13 19:54 UTC, issy requested changes

2021-02-13 19:54 UTC, issy commented on unity_cogs/react_report.py
> +        if payload.emoji.name != "⚠️":
This should also return if the event is not in a guild

2021-02-13 19:54 UTC, issy commented on unity_cogs/react_report.py
> +        if payload.emoji.name != "⚠️":
Should also return if not in guild

2021-02-13 19:54 UTC, issy commented on unity_cogs/react_report.py
> +                report_retracted = False
Could return here instead of breaking the loop and then returning

2021-02-13 21:09 UTC, jzyrobert commented on unity_cogs/react_report.py
> +        if payload.emoji.name != "⚠️":
Should the emoji be a config choice? Or at least be defined at the top of the file?

2021-02-14 21:29 UTC, issy approved these changes

2021-02-14 21:30 UTC, merged